### ISSUE TITLE
Can’t change text color

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#10]
I tried to change the “bg-color” and “fg-color” commands in the config file, and even as launch options, but they have no effect. I also can’t disable the screen flash in the config file, but only when using the launch options does it work. Here’s my config file.

https://gist.github.com/shoober420/8a2206ee8472eb0b74aa7dec969f0ccc

**Comment by freed00m** [comment]
I noticed this as well, I think when a theme is set no color changes are applied. It was more than 10 commits ago, so not sure if it still behaves like that.

Surely all colors should be overwritteable even if themes is configured.

**Comment by 91861** [comment]
In the config file colors can be set with `="#00ff7f"` or `=00ff7f` as `#` starts a comment (which is confusing and will be changed). Everything else resolved by 5c3555db57a380daa6a037be2312b107130fe653.

**Comment by shoober420** [comment]
Awesome, I was just tweaking my config now and noticed I did forget to add in the quotes for those commands. Thank you very much sir, everything is working.
