### ISSUE TITLE
Implicit function "strtof32" when build on musl.

### ISSUE THREAD

**Issue by lidgnulinux** [91861/wayst#111]
Hello, I got an error about implicit function (strtof32) when build on alpine linux. Alpine linux is using musl. I tried to replace `strtof32` with `strtob2` on `src/settings.c` and it's compiled successfully. 

```
                // float val = strtof32(buf.buf, NULL);
                float val = strtob2(buf.buf, NULL);
```

Is this correct or not ? Thanks.

**Comment by 91861** [comment]
It should be `strtof`.
