### ISSUE TITLE
Highlighted text after click focus 

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#13]
When clicking to another window to active focus, the text that happened to be highlighted at that time will remain highlighted.

![BFA621D2-F602-44BD-ADAF-F28A8517377D](https://user-images.githubusercontent.com/5150898/86523536-fae6d080-be3b-11ea-9a4a-e94aecaeded8.jpeg)

**Comment by 91861** [comment]
Isn't keeping selection highlighted on focus loss the correct behavior?

If the problem is that the highlighted region is not moved on window resize, it was fixed by c385103c6e01aa3fe19244be6432930a3a5d1a6a.

**Comment by shoober420** [comment]
@91861 

Yes, this did happen after a window resize actually. Thank you very much.
