### ISSUE TITLE
Ctrl+Shift+P will paste and trigger Enter key

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#20]
When attempting to paste the text using the vim like yank method, pressing Ctrl+Shift+P will trigger the enter key.

**Comment by 91861** [comment]
Extra new line characters when pasting multiple lines of text should be fixed by d7617823be877efbb6fc599ec01f656ed1b6f912.

**Comment by shoober420** [comment]
Thank you, it’s fixed
