### ISSUE TITLE
Ctrl+Shift+Y pastes clipboard text

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#22]
When one uses the clipboard method of pasting prior, then chooses to use the vim like yank method afterward, pressing Ctrl+Shift+Y will activate the clipboard paste key combo (Ctrl+Shift+V).

Vim like yank works fine until the clipboard method is used.

**Comment by 91861** [comment]
I can't reproduce the problem. Is this issue still relevant?

**Comment by shoober420** [comment]
Yes, it still happens for me.

So here is my test scenario.

1. Use cat, and output a files text.
2. Use clipboard copy to paste output in terminal (Ctrl+Shift+C then Ctrl+Shift+V).
3. After pasting text with clipboard method, then attempt to to the vim yank method (Ctrl+Shift+Y).
4. When hitting the yank key combo, the clipboard text with be pasted instead of the highlighted text being yanked.

**Comment by 91861** [comment]
Duplicate of #26.

**Comment by shoober420** [comment]
Whoops, my fault.
