### ISSUE TITLE
Resizing wayst window size, happens only if focused

### ISSUE THREAD

**Issue by freed00m** [91861/wayst#35]
Using a tiling WM, users can resize window without having a focus on it. (Like active window shrinks then non active window expands.)

Wayst if not focused wont expand content, but onlyu if it was previously focused.

Reproduction:
Open two wayst terminals in Tiling WM, make focus on both windows ( so they write their last know sizes ), then shrink the active wayst window and observe the non-focused terminal not size adjusted. 

![2020-07-14-232011_grim](https://user-images.githubusercontent.com/9461698/87477560-9809ec00-c628-11ea-91a6-3c71f58deadf.png)

**Comment by freed00m** [comment]
It seems all drawing is stopped.

**Comment by 91861** [comment]
The problem with this is that redrawing when the window is offscreen will block until the window is mapped again, stop the interpreter and cause #33. Sway is not sending wl_surface::leave events when moving windows to other workspaces (I'm not sure if it should or if it's a bug, gnome for example does and 97045b7d14e44af7e5a16ca706d9e048e4f670c8 works fine there) so there is no way that I know of to detect if the window can be repainted.

**Comment by freed00m** [comment]
@91861 well all rendering stops when I leave the focus even on the same workspace, that would make the terminal completely unuseable.

Well some workspaces can be off screen

That [97045b7](https://github.com/91861/wayst/commit/97045b7d14e44af7e5a16ca706d9e048e4f670c8) commit fixed it even on wlroots/sway, so thx, do you think we should ask @emersion for opinnion ?

And #33 still sometimes happens with it.

**Comment by emersion** [comment]
>Sway is not sending wl_surface::leave events when moving windows to other workspaces (I'm not sure if it should or if it's a bug, gnome for example does and 97045b7 works fine there) so there is no way that I know of to detect if the window can be repainted.

wl_surface.leave should *not* be used for this purpose. Even on GNOME there are cases where wl_surface.leave isn't sent and the window shouldn't be repainted, I bet when the window is hidden behind other windows for instance.

Instead wl_surface.frame should be used. See: https://emersion.fr/blog/2018/wayland-rendering-loop/

**Comment by emersion** [comment]
Opened https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/86 to make this clear in the protocol.
