### ISSUE TITLE
Cut off text at certain font sizes

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#36]
At font sizes 10, 12, 17, 25 (slightly) and 28 (slightly), the text will be cut off. ~~Also, the terminal still appears to not incorporate all of the space in the window as previously reported.~~
![8468FF10-18F4-43F8-AD51-FFE0B91552BD](https://user-images.githubusercontent.com/5150898/87489932-4e160b80-c612-11ea-901d-7274b114ef3c.jpeg)

**Comment by 91861** [comment]
>Also, the terminal still appears to not incorporate all of the space in the window

As far as i know this works correctly, just like any other terminal.
![image](https://user-images.githubusercontent.com/61886778/87491060-6a806b00-c647-11ea-94cb-2956cb0ee6c4.png)
alacritty, kitty, wayst

**Comment by shoober420** [comment]
You’re right, my apologize. That is the normal behavior. But with the most recent commit, the text gets cut off at those mentioned font sizes. I use IBM Plex Mono.
