### ISSUE TITLE
PSF Font Support

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#38]
This might be an impossible request, but is it possible for Wayst to use the PSF fonts that are used in the TTY? On Arch, the fonts are located in the ```/usr/share/kbd/consolefonts/``` directory. Example fonts here would be ``` sun12x22.psfu.gz```, ``` drdos8x16.psfu.gz```, and ``` default8x16.psfu.gz```.

**Comment by 91861** [comment]
It's not impossible, but freetype doesn't support PSF so it would require writing a custom loader. I don't think it's worth it. Most PSF fonts are available in other formats or can be converted ([psf2bdf](https://aur.archlinux.org/packages/psftools)).

**Comment by shoober420** [comment]
Ok, Thanks for the information, I’ll check out that program.
