### ISSUE TITLE
Dead keys are unhandled, renders tilde with extra space.

### ISSUE THREAD

**Issue by freed00m** [91861/wayst#4]
The czech layout relies requires to use dead keys for letters `ť ň ` 

Short explanation, when you press dead key for `ˇ` a character is not put on display and awaits next character to be chosen, if then type `n` you'll get `ň` which does not exist on keyboard as separate key.
When dead key is pressed, the (~) tilde + some extra space is rendered.

For comparsion, Alacritty vs Wayst, Wayst is on top.

![2020-06-11-214916_selection](https://user-images.githubusercontent.com/9461698/84432625-5ce15b00-ac2d-11ea-8488-b07642601be6.png)

To test dead key, try to pres LSHIFT + (+ sign usually next to backspace), then release and press (n)

Layout options
```
# Set keyboard layout 
XKB_DEFAULT_LAYOUT=cz
XKB_DEFAULT_VARIANT=qwerty
XKB_DEFAULT_OPTIONS=ctrl:nocaps
```

**Comment by 91861** [comment]
Did be456de0305a4c534bb55eceb6e64bde575d38e6 fix this? Not sure if I'm testing this properly.

**Comment by freed00m** [comment]
@91861 No sorry, it just skips all dead keys, making them not work at all.
