### ISSUE TITLE
font-symbol bug

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#41]
I'm currently trying to use `font-fallback` for certain missing charactors in a font set, but Wayst seems to ignore my desired option. When setting the main `font` option to `PxPlus_IBM_VGA_8x16.ttf`, the font will load. But when used for the `font-fallback` option, no changes are made to the missing glyphs. The font and missing glyphs are loaded when using the main `font` option.

Config:
https://gist.github.com/shoober420/8a2206ee8472eb0b74aa7dec969f0ccc

**Comment by 91861** [comment]
`font-fallback` was renamed to `font-symbol` and `font-fallback2` to `font-color`.

**Comment by shoober420** [comment]
A new issue has arose. Using both `font-symbol` and font-color are ineffective to drawing the missing glyphs in cmus for me. The desired font, PxPlus_IBM_VGA_8x16, will only render the missing glyphs when it’s set with “font”.

font:
![7FE882C3-1747-453D-B358-54ED143C3E77](https://user-images.githubusercontent.com/5150898/88437601-cb8d0900-cdd4-11ea-89f0-ef55faf6bbb1.jpeg)

font-symbol / font-color:
![227E3C7B-ED0E-447B-8C14-020DD5A08758](https://user-images.githubusercontent.com/5150898/88437660-efe8e580-cdd4-11ea-9c48-aab97fb3c4c0.jpeg)

**Comment by shoober420** [comment]
I figured it out. I left the underscores in the font name, so the font never loaded. This actually works perfectly fine. Thank you very much and sorry for the confusion.

![5CFDBDE0-92C4-47F7-818B-056EC8335BFE](https://user-images.githubusercontent.com/5150898/89686418-54736c80-d8cc-11ea-82a3-d8cea2b95281.jpeg)
