### ISSUE TITLE
Continiuous mode for key presses

### ISSUE THREAD

**Issue by Narrat** [91861/wayst#43]
Hi and thank you for this terminal emulator.
One thing that is currently bothering me: If I want to remove a text I need to press and release backspace for every glyph/char I want to remove, instead of just keep pressing down the backspace key. This example applies for every key.
Can this behaviour be added or is there already a way to configure this and overlooked it?

Best regards

**Comment by 91861** [comment]
Key repeating _should_ work normally.
Does this happen on xorg or wayland (what compositor)?

**Comment by Narrat** [comment]
Happens on wayland with hikari as the compositor

**Comment by Narrat** [comment]
Works like a charm. Thank you very much
