### ISSUE TITLE
Broken characters after running htop

### ISSUE THREAD

**Issue by orhun** [91861/wayst#44]
Hi, nice project :+1: 

I was trying it out and wanted to see my system stats and simply ran htop. It looks like it broke the terminal characters/font.

![t](https://user-images.githubusercontent.com/24392180/88434387-b92cc280-ce08-11ea-93ad-bb0615d12487.jpg)

![t](https://user-images.githubusercontent.com/24392180/88434490-f09b6f00-ce08-11ea-814d-63d56c5afd63.jpg)

My default terminal on the left and wayst on the right.

Is it a font issue?

**Comment by 91861** [comment]
>Is it a font issue?

Looks like some problem with the interpreter, possibly caused by something in PS1. Does this happen when running  `./wayst -x htop` ?

**Comment by orhun** [comment]
Nope, it didn't happen at all.

![t](https://user-images.githubusercontent.com/24392180/88456599-65ad8980-ce87-11ea-8315-735e4fc75acf.jpg)

**Comment by 91861** [comment]
If e4ae37b962856ab6d80530db27d73c4699ff484c didn't fix it, what is the output of `./wayst --debug-pty` when starting htop from the shell?

**Comment by orhun** [comment]
It didn't fix it.
Logs: [wayst.log](https://github.com/91861/wayst/files/5003235/wayst.log)
