### ISSUE TITLE
DejaVu Sans rendering bug

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#45]
~~I know this font is a little wacky, but I love old school fonts. This font, and many other PSF fonts have predetermined font sizes because of being designed for console TTY. This is probably why it renders incorrectly. Its the TTF version.~~

Here’s their website.
https://int10h.org/ - [AUR](https://aur.archlinux.org/packages/oldschool-pc-fonts/)

Config:
https://gist.github.com/shoober420/8a2206ee8472eb0b74aa7dec969f0ccc

~~`PxPlus_IBM_VGA_8x16.ttf`~~
`DejaVu Sans Book`

![CB5F8AB3-A38D-4567-A500-1F34F3CC41CA](https://user-images.githubusercontent.com/5150898/88445096-91306580-cdee-11ea-90ed-ff816d83eab1.jpeg)

**Comment by shoober420** [comment]
My apologize! I figured out what’s going on. I kept the underscore in the fonts name in my config, so the font didn’t even load. The font being used in the picture, is actually `DejaVu Sans:Book`.

![E2F4FFF7-6AD7-4C1B-A7B3-FBE38BC4D683](https://user-images.githubusercontent.com/5150898/89685955-64d71780-d8cb-11ea-89bf-29d320a030f7.jpeg)

**Comment by 91861** [comment]
`DejaVu Sans` is a not a monospaced font.

**Comment by shoober420** [comment]
This font renders fine now, closing.
