### ISSUE TITLE
vim freezes after pasting large amounts of text

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#53]
When copying and pasting large amounts of text in vim, wayst will freeze. A sigkill is necessary to close wayst.

Here is the crash with an intentional wrong setting (g-fb-color="#0077f7")
[waystbug5.txt](https://github.com/91861/wayst/files/5114495/waystbug5.txt)

Here is a crash with a good config.
[waystbug6.txt](https://github.com/91861/wayst/files/5114497/waystbug6.txt)

Another one for good measure.
[waystbug7.txt](https://github.com/91861/wayst/files/5114501/waystbug7.txt)

**Comment by shoober420** [comment]
This will still occur, but it takes substantially a lot more text of pasting to occur than previously.

**Comment by freed00m** [comment]
@shoober420 maybe uploading some file that causes this?

**Comment by shoober420** [comment]
I just compiled from the latest master (https://github.com/91861/wayst/commit/c993c79e088802395d4f15556a2ccf4920701ea6), and pasting lots of text in vim will still freeze wayst. 

I have a crude way of testing. I simply copy a modest sized shell script, then spam paste it into vim holding down “Ctrl+Shift+V”. Wayst used to crash doing this method, but is now resilient. However, doing this into vim still freezes wayst.

**Comment by freed00m** [comment]
Could be, try pasting in nano or nvim. :)

**Comment by shoober420** [comment]
It doesn’t freeze nano, although it keeps the text all on one line instead of scrolling down the screen like vim and the terminal. So I launched vi and did the test, and it did not freeze. This must be a bug with vim. Thank you for the tips.
