### ISSUE TITLE
wayst crash using NVIDIA

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#56]
I recently put together my Xorg machine, as compared to my Wayland machine, and noticed that the latest master crashes on launch with an error.

```[warning] Freetype has no clear type support```

Latest master works on my Wayland machine. using the `--debug-pty` command have no additional output.

**Comment by freed00m** [comment]
I just want to add that around commit 123-126 there was issue on starting on wayland as well.

Fails to create a EGL context but only on Intel graphics, on my AMD it works. I am trying to figure out a missing dep. maybe.

```
wayst
[warning] Freetype has no clear type support
[error] failed to create EGL context
```

**Comment by shoober420** [comment]
To further add, my Wayland machines do use AMD, so this must be an issue with NVIDIA and Intel, instead of Xorg and Wayland.

**Comment by shoober420** [comment]
I just compiled the latest master (https://github.com/91861/wayst/commit/fc31b41048b19553367e2becdb8fdd3528f5e926), and I’m still crashing. I still get no error messages in debug mode.

**Comment by shoober420** [comment]
As of the latest git master (https://github.com/91861/wayst/commit/952f8765dd5fa9d1df84e480fc532a0673fa48e2), I’m still crashing at launch.

**Comment by 91861** [comment]
Could you provide a backtrace?

**Comment by shoober420** [comment]
Here are two logs using strace with two different compile options.

`default options`
[wayststracewayland.txt](https://github.com/91861/wayst/files/5147584/wayststracewayland.txt)

`window_protocol=x11`
[wayststracex11.txt](https://github.com/91861/wayst/files/5147588/wayststracex11.txt)

**Comment by shoober420** [comment]
As of the latest master commit (https://github.com/91861/wayst/commit/2070d64fa7ad7500c077418b87f872529a89efa3), I get these errors at startup then crash. Should I do another strace?
![4A43F4C0-0616-423E-94DD-CDAA6B82BDCA](https://user-images.githubusercontent.com/5150898/92840567-41622980-f3af-11ea-8639-c4aa46cc6118.jpeg)

**Comment by shoober420** [comment]
For some information, I have Xwayland disabled on my a Xserver.

**Comment by shoober420** [comment]
This bug has disappeared. Wayst works great on Xorg.
