### ISSUE TITLE
cursor vanishing in keyboard select mode

### ISSUE THREAD

**Issue by Narrat** [91861/wayst#59]
Hi.
With a wayst build based on 18a038b3531a7374a691731f6707c44dd76ef62a the cursor won't be visible anymore after entering the first line of the scrollback buffer. Will appear again either via leaving the mode or moving the cursor back to the bottom.

Unrelated question: Will there be extensions to this mode? Or dedicated shortcuts for scrolling? Like Ctrl(+Shift)+Page-Up/-Down most commonly found with vte based terminals.

**Comment by 91861** [comment]
> cursor won't be visible

> dedicated shortcuts for scrolling

Fixed in 7d5d676919f78e29292872420c9eafa118ad2e9e.


> Will there be extensions to this mode?

Sure, I can add more movement commands.

**Comment by Narrat** [comment]
Works like a charm :) Thanks a lot
And the rework has the additional positive benefit that the `del` key is now working for me.
> Sure, I can add more movement commands.

Sounds great
