### ISSUE TITLE
wayst depends on libwayland-client.so.0

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#61]
When trying to launch wayst on a pure Xorg machine with no Xwayland installed, wayst still depends on the libwayland-client.so.0 library to launch.  I even built wayst with the “window_protocol=x11” compile option, and it still depends on it.

**Comment by 91861** [comment]
What is the output of `lddtree wayst` (arch package pax-utils) after clean building with `make -B window_protocol=x11`?
Doesn't seem to happen on my setups. Maybe it's a driver thing?

**Comment by shoober420** [comment]
That fixed it. I must have added the compile option to the PKGBUILD incorrectly. Thank you. I’m for certain this is related to my other issue (https://github.com/91861/wayst/issues/56).
