### ISSUE TITLE
Feature request: config option for cursor style

### ISSUE THREAD

**Issue by etenim** [91861/wayst#63]
As an example:

`--cursor-style <string>    Cursor style (default: [])`

Optionally setting the cursor style to something other than the standard white box. Thinking of an underscore _ for a more minimalist type cursor.

Having it be a string type might not be appropriate. Possibly just an enable/disable setting if the choice would simply be between the default box and an underscore, rather than an arbitrary setting with other options.

Thank you for a very nice terminal emulator!

**Comment by 91861** [comment]
> Having it be a string type might not be appropriate.

The cursor is not rendered as regular text so this would be difficult.

It can draw the three standard cursor types and we could do something like this:
`--cursor-style <name:bool?> Set initial cursor style - block/beam/underline:blinking (default: block:true)`

**Comment by etenim** [comment]
> It can draw the three standard cursor types and we could do something like this:
> `--cursor-style <name:bool?> Set initial cursor style - block/beam/underline:blinking (default: block:true)`

That would be perfect, thank you.
