### ISSUE TITLE
hide title bar

### ISSUE THREAD

**Issue by ziyouwa** [91861/wayst#71]
Can you add the function of hiding the title bar?
Add option:
hide_titlebar=true
etc.

**Comment by Narrat** [comment]
Just asking out of curiosity: Isn't this something which should be covered by the X window manager or wayland compositor in question?

**Comment by 91861** [comment]
> Isn't this something which should be covered by the X window manager or wayland compositor in question?

It is, but the client can request what type of decorations it wants.

**Comment by ziyouwa** [comment]
Thank you very much!
