### ISSUE TITLE
copy and paste bug

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#75]
When copying and pasting a string of text, there will sometimes be a space added in between letters.

For example, “gobj ect-introspection” is pasted when copying this script.

https://gist.github.com/shoober420/8e8cc853ce180a1fe4d8343f4dffe2a2

**Comment by 91861** [comment]
If this is related to line wrapping, it was probably fixed by 565b1f9.

**Comment by shoober420** [comment]
I just tested with latest commit, and this still is happening.

**Comment by shoober420** [comment]
Commit https://github.com/91861/wayst/commit/2c3a87c60c7856a14142a025425ff50976c5b6ea fixed this bug. Thank you very much.
