### ISSUE TITLE
First shortcut(s) in vim not recognized/accepted

### ISSUE THREAD

**Issue by Narrat** [91861/wayst#76]
Noticed a small issue, which came up somewhere between the commits 6be9707 (still good) and 57d25d7 (bad). Sadly I couldn't bisect it, as it fails compiling (no rule for fmt.h).
What do I notice? If I start vim and want for example into the interactive modus, I need to press `i` three times before the interactive modus is entered. Double commands like `dd` are also working after the third keypress.
After this initial hiccup every shortcut works as expected. It is just this initial one. Oh and to make it even more curious, commands (everything starting with `:`) aren't affected.

**Comment by 91861** [comment]
Vim was getting confused by a wrong response to DECRQM. Fixed by f475e256ca1a7595686443726ffef61aeabbe2bf.


> fails compiling (no rule for fmt.h)

run `make cleanall` before rebuilding.
I guess the `.d` files are not getting updated when new headers are added.

**Comment by Narrat** [comment]
Fix works like a charm. Thank you.

> run `make cleanall` before rebuilding.

That did the trick. Didn't think of that. Only `make clean`.
