### ISSUE TITLE
New rendering doesn't always recognize change in window size

### ISSUE THREAD

**Issue by Narrat** [91861/wayst#83]
Got around to generate a build of latest master.
And with the new rendering I noticed something is off with the compositor hikari.

![wayst_rendering](https://user-images.githubusercontent.com/2787518/109545255-e93bf280-7ac8-11eb-8701-51a89b5eda29.png)

The picture tries to show, that the big terminal window still renders the content in the area of it's initial size. It kinda didn't get the changed window geometry? (`ls` on `/proc`. so enough stuff to fill screens)
Although with manually resizing a terminal window, it seems to work... So not really sure who is at fault, but as it worked before, I wanted to start at this place

**Comment by alexmat** [comment]
I'm having the same issue running sway 1.5.1

I reverted to https://github.com/91861/wayst/commit/fd91890a40a70de392dac4fbaf82df7c4007006c and the issue goes away
